resource_type:
  - name: discord-notification-resource
    type: registry-image
    source:
      repository: logsquaredn/discord-notification-resource
      tag: latest

resources:
  - name: discord-notification-resource
    type: git
    icon: github
    check_every: 30m
    source:
      uri: https://github.com/logsquaredn/discord-notification-resource/
      branch: master

  - name: discord-notification-resource-image-alpine
    type: docker-image
    icon: docker
    check_every: 1h
    source: 
      username: ((docker.username))
      password: ((docker.password))
      repository: ((docker.username))/discord-notification-resource
      tag: alpine

  - name: discord-notification-resource-image-ubuntu
    type: docker-image
    icon: docker
    check_every: 1h
    source:
      username: ((docker.username))
      password: ((docker.password))
      repository: ((docker.username))/discord-notification-resource

  - name: discord-notification-resource-test
    type: discord-notification-resource
    icon: test-tube
    check_every: 9999h
    source:
      webhook_id: ((discord.webhook.id))
      token: ((discord.webhook.token))

  - name: version
    type: semver
    icon: tag
    check_every: 9999h
    source:
      initial_version: 0.0.1
      driver: s3
      bucket: ((aws.s3.bucket))
      key: ((aws.s3.keys.version))
      access_key_id: ((aws.s3.access_key.id))
      secret_access_key: ((aws.s3.access_key.secret))
      region_name: ((aws.s3.region))

  - name: vars
    type: s3
    icon: cog
    check_every: 30m
    source:
      bucket: ((aws.s3.bucket))
      regexp: ((aws.s3.keys.vars))
      access_key_id: ((aws.s3.access_key.id))
      secret_access_key: ((aws.s3.access_key.secret))
      region_name: ((aws.s3.region))



anchors:
  - &default_job_config
    build_log_retention:
      builds: 12
      minimum_succeeded_builds: 3
    serial: true

  - &build_args
    WEBHOOK_ID: ((discord.webhook.id))
    WEBHOOK_TOKEN: ((discord.webhook.token))



jobs:
  - name: update-pipeline
    <<: *default_job_config
    plan:
      - in_parallel:
        - get: discord-notification-resource
          trigger: true

        - get: vars
          trigger: true

      - set_pipeline: self
        file: discord-notification-resource/cicd/pipelines/discord-notification-resource.yml
        var_files: ((var_files))


  - name: build-discord-notification-resource-image-alpine
    <<: *default_job_config
    plan:
      - in_parallel:
        - get: discord-notification-resource
          passed: [update-pipeline]
          trigger: true

        - get: version

      - put: discord-notification-resource-image-alpine
        params:
          build: discord-notification-resource/
          tag_as_latest: false
          cache: true
          dockerfile: discord-notification-resource/dockerfiles/alpine/Dockerfile
          tag_file: version/version
          tag_prefix: alpine-
          additional_tags: discord-notification-resource/dockerfiles/alpine/additional_tags
          build_args: *build_args
        get_params:
          skip_download: true


  - name: build-discord-notification-resource-image-ubuntu
    <<: *default_job_config
    on_success:
      in_parallel:
        - put: version
          params:
            bump: patch
        
    plan:
      - in_parallel:
        - get: discord-notification-resource
          passed: [update-pipeline]
          trigger: true

        - get: version

      - in_parallel:
        - put: discord-notification-resource-image-ubuntu
          params:
            build: discord-notification-resource/
            tag_as_latest: true
            cache: true
            dockerfile: discord-notification-resource/dockerfiles/ubuntu/Dockerfile
            tag_file: version/version
            tag_prefix: ubuntu-
            additional_tags: discord-notification-resource/dockerfiles/ubuntu/additional_tags
            build_args: *build_args
          get_params:
            skip_download: true

        - put: discord-notification-resource-test
          params:
            content: new version successful
